### ISSUE TITLE
File I/O Closing files to have them stop writing and not making empty files

### ISSUE THREAD

**Issue by bioSandMan** [dstreett/PruNe#1]
If I run the basic command:

../prune -1 fastqFiles/prune_R1.fastq -2 fastqFiles/prune_R2.fastq -N -F

then I get files out but I also get a warning:

Within fileWriter.cpp setTab() - stdout, fastq, or interleaved all ready set
Please, only set one type of output, either fastq, interleaved, tab, or stdout (stdout is always tab)

If I leave the files that were written out and then rerun the same command, the only difference being tha the files from the first command now exist in the directory that I'm running it, then I get the expected output:

PE_Reads        PE_Kept Avg_PE_Left_Trim        Avg_PE_Right_Trim       R1_Discarded    R2_Discarded    SE_Reads        SE_Kept Avg_SE_Left_Trim        Avg_SE_Right_Trim       Run_Time
2500.000000     2500.000000     65.71   65.71   0.000000        0.000000        0.000000        0.000000        nan     nan     0

I get the same kind of behavior with ATtack.

**Comment by dstreett** [comment]
Hey @bioSandMan .  Good catch. I forgot to close the file - I will throw that in there real quick. Additionally, I just changed this to file I/O so I don't make empty files any more as well.

Thanks again.

**Comment by dstreett** [comment]
All right, it should be fixed up! Let me know if there are any issues.
